version: "alpine"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile

  nginx:
    image: nginx:latest
    build: ./nginx/
    depends_on:
      - web
    ports:
      - 8080:8080