version: "alpine"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile

  nginx:
    image: nginx:latest
    volumes:
      - nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    ports:
      - 8080:8080